### ISSUE TITLE
Nerf Hulk

### ISSUE THREAD

**Issue by voces** [voces/fixus#69]
For each level, Hulk should:
- Get slower movement speed. Say 2/level.
- Get slightly larger. Say 0.03/level.

**Comment by XXXandBEER** [comment]
I'd prefer to see Hulk balanced instead of nerfing other unrelated traits. Unless you're going to add a negative for all other classes. I.e maybe engineer can't save.

**Comment by voces** [comment]
So right now Hulk gets 15 passive health per level; I forgot exactly what Avatar does (15?); what would be your suggestion for nerfing the bonuses?

**Comment by XXXandBEER** [comment]
Right now hulk gets 35 HP after 1 save then +25 from avatar. Wolf base damage is less than 1 save hulk I believe. I would make it +10 hp per level, and then avatar doubles your health.

Alternative: remove passive HP bonus, and instead give a passive aura that increases life regen on nearby allies and structures.

**Comment by voces** [comment]
Went with:

Passive: 10 hp/level
Active: 2 armor/level

This gives the following effective HP table. Note that magic damage bypasses armor and these are without aura effects.
old base | old avatar | new base | new avatar
-- | -- | -- | --
35 | 60 | 30 | 34
50 | 100 | 40 | 50
65 | 140 | 50 | 68
80 | 180 | 60 | 89
95 | 220 | 70 | 112
110 | 260 | 80 | 138
125 | 300 | 90 | 166
140 | 340 | 100 | 196
155 | 380 | 110 | 229
170 | 420 | 120 | 264
185 | 460 | 130 | 302
200 | 500 | 140 | 342
215 | 540 | 150 | 384
230 | 580 | 160 | 429
245 | 620 | 170 | 476
260 | 660 | 180 | 526
275 | 700 | 190 | 578
290 | 740 | 200 | 632
305 | 780 | 210 | 689
320 | 820 | 220 | 748
335 | 860 | 230 | 810
350 | 900 | 240 | 874
365 | 940 | 250 | 940
380 | 980 | 260 | 1009
395 | 1020 | 270 | 1080
